name: Java CI with Maven

# 🔹 Коли запускати pipeline
on:
  push:       # коли є пуш у репозиторій
    branches: [ "*" ]
  pull_request:  # або при створенні pull request
    branches: [ "*" ]
  workflow_dispatch:  # дозволяє вручну запустити pipeline у GitHub Actions

# 🔹 Основна джоба
jobs:
  build-and-test:
    runs-on: ubuntu-latest   # runner (віртуальна машина GitHub)

    steps:
      # 1️⃣ Завантаження коду
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Встановлення JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3️⃣ Кешування Maven-залежностей (щоб швидше збиралося)
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # 4️⃣ Збірка та тести
      - name: Build and run tests
        run: mvn clean test -Dsurefire.useFile=false

      # 5️⃣ Завантаження звітів (якщо є Allure)
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/